version: '3'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - logs
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    environment:
       ELASTICSEARCH_HOSTS: http://es01:9200
    ports: 
      - 5601:5601
    networks:
      - logs
    depends_on: 
      - es01
  # Api .net Core
  api:
    image: logapi
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - ASPNETCORE_ENVIRONMENT=Docker  
    ports: 
      - 8081:80
    networks: 
      - logs
    depends_on: 
      - kibana

volumes:
  data01:
    driver: local
  


networks:
  logs: