name: Build Git

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: docker://mcr.microsoft.com/dotnet/core/sdk:3.1.302-buster
    - name: Restore packge
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Run Tests
      run: dotnet test
   
