name: BulidGit

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: docker://mcr.microsoft.com/dotnet/core/sdk:2.2
    - name: Restore packge
      run: dotnet restore
    - name: Buld
      run: dotnet build
    - name: Run Tests
      run: dotnet test
   
